### ISSUE TITLE
Geant4 (and others) are not setup correctly

### ISSUE THREAD

**Issue by tdealtry** [hyperk/hk-software#3]
Currently, `setup.sh` basically just adds the relevant `bin` and `lib` directories to `$PATH` and `$LD_LIBRARY_PATH` respectively

This is fine for simple packages, but others require more
- `geant4.sh` does the `$PATH` & `$LD_LIBRARY_PATH` stuff, but then also sets up the data variables (WCSim won't run without these G4 data variables set)
- `this_wcsim.sh` does the `$PATH` & `$LD_LIBRARY_PATH` stuff, but also sets up `$ROOT_INCLUDE_PATH`, `$WCSIM_BUILD_DIR`, and most importantly `$WCSIMDIR` (there's some source code that looks for mPMT geometry info in files relative to `$WCSIMDIR`)
- `thisroot.sh` does the `$PATH` & `$LD_LIBRARY_PATH` stuff, but also then sets up some other similar variables (e.g. `$PYTHONPATH`) and sets `$ROOTSYS` (not sure if this is required for anything?)

So the question is, for the packages that have a setup script, shouldn't we use the setup script?

**Comment by guiguem** [comment]
Resolved in hk-pilot https://github.com/hyperk/hk-pilot/commit/361399206f3a2a0179f6e0fbf3ec618d5ebeca1c
